import { build } from 'esbuild';
import fs from 'fs';
import path from 'path';
import { nodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill';
import { nodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
import jsonPlugin from '@esbuild-plugins/json';

const vault_plugin_dir = fs.existsSync('./.vault_plugin_dir') ?
    fs.readFileSync('./.vault_plugin_dir').toString().trim() :
    '.';

const banner = `/*
@preserve
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

async function buildPlugin() {
    await build({
        entryPoints: ['src/main.tsx'],
        outdir: vault_plugin_dir,
        bundle: true,
        format: 'cjs',
        sourcemap: 'inline',
        minify: true,
        banner: { js: banner },
        define: {
            'process.env.NODE_ENV': '"production"',
        },
        plugins: [
            jsonPlugin(),
            nodeModulesPolyfillPlugin(),
            nodeGlobalsPolyfillPlugin(),
            // For copying manifest.json you can do a separate script after build
        ],
        external: [
            'obsidian',
            "codemirror",
            "@codemirror/autocomplete",
            "@codemirror/closebrackets",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/comment",
            "@codemirror/fold",
            "@codemirror/gutter",
            "@codemirror/highlight",
            "@codemirror/history",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/matchbrackets",
            "@codemirror/panel",
            "@codemirror/rangeset",
            "@codemirror/rectangular-selection",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/stream-parser",
            "@codemirror/text",
            "@codemirror/tooltip",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/lr"
        ],
        loader: {
            '.ts': 'ts',
            '.tsx': 'tsx',
            '.json': 'json'
        },
        watch: process.argv.includes('--watch'),
    });

    // Copy manifest.json manually if needed
    if (vault_plugin_dir !== '.') {
        fs.copyFileSync('manifest.json', path.join(vault_plugin_dir, 'manifest.json'));
    }
}

buildPlugin().catch((e) => {
    console.error(e);
    process.exit(1);
});
